import { useState } from 'react';
import { DemoBar, Icon, Modal, imagePath } from '../../shared/ui.jsx';
import '../../shared/base.css';
import './styles.css';

const services = [
  { name:'Budowa domów', icon:'house', text:'Od pierwszego wykopu po klucze do własnego domu. Koordynacja etapów, materiałów i pracy zespołu.', points:['Stan surowy i deweloperski','Harmonogram dopasowany do inwestycji'] },
  { name:'Remonty kompleksowe', icon:'shield', text:'Nowy rozdział dla Twojej nieruchomości. Przemyślany zakres i jeden zespół odpowiedzialny za całość.', points:['Domy, mieszkania i lokale','Instalacje i prace wykończeniowe'] },
  { name:'Wykończenia wnętrz', icon:'check', text:'Detale, które zmieniają przestrzeń w dobre miejsce do życia. Estetyczne i staranne wykonanie.', points:['Łazienki, podłogi i zabudowy','Realizacja według projektu'] },
  { name:'Elewacje i ocieplenia', icon:'house', text:'Trwała ochrona budynku i spójny wygląd. Dobór rozwiązań do potrzeb domu oraz budżetu.', points:['Ocieplenie i tynki elewacyjne','Modernizacja istniejących budynków'] },
  { name:'Adaptacje poddaszy', icon:'arrow', text:'Więcej miejsca bez zmiany adresu. Wykorzystaj potencjał przestrzeni, którą już masz.', points:['Izolacja i zabudowy','Nowe układy pomieszczeń'] },
  { name:'Doradztwo budowlane', icon:'clock', text:'Jasne odpowiedzi przed rozpoczęciem prac. Pomagamy określić zakres i kolejne kroki inwestycji.', points:['Omówienie potrzeb i zakresu','Wstępny plan realizacji'] },
];
const projects = [
  { name:'Dom pod lasem', category:'Domy', image:'house', location:'Katowice', area:'180 m²', year:'2025', text:'Nowoczesny dom jednorodzinny z dużymi przeszkleniami. Przykładowa realizacja od stanu surowego do wykończenia.' },
  { name:'Miejska przestrzeń', category:'Wnętrza', image:'living', location:'Gliwice', area:'92 m²', year:'2025', text:'Jasne wnętrze z naturalnymi materiałami. Przykładowy remont i aranżacja strefy dziennej.' },
  { name:'Dom otwarty na światło', category:'Wnętrza', image:'home', location:'Tychy', area:'145 m²', year:'2026', text:'Otwarta przestrzeń z widokiem na ogród. Przykładowe wykończenie domu w nowoczesnym stylu.' },
];

function QuoteForm({ service, setService }) {
  const [receipt, setReceipt] = useState(null);
  const [error, setError] = useState('');
  function submit(e) {
    e.preventDefault(); setError('');
    const data = Object.fromEntries(new FormData(e.currentTarget));
    if (data.name.trim().length < 2 || data.city.trim().length < 2) return setError('Podaj imię i nazwisko oraz miejscowość inwestycji.');
    if (data.description.trim().length < 20) return setError('Opisz planowane prace w co najmniej 20 znakach.');
    if (data.phone && !/^[+\d\s()-]{7,20}$/.test(data.phone)) return setError('Sprawdź numer telefonu lub pozostaw to pole puste.');
    if (!services.some(s => s.name === data.service)) return setError('Wybierz usługę z listy.');
    setReceipt({ name:data.name.trim(), service:data.service, city:data.city.trim(), area:data.area, budget:data.budget, reference:`NB-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,6).toUpperCase()}` });
  }
  return <section className="quote-section" id="wycena"><div className="container quote-layout"><div><span className="eyebrow">ZACZNIJMY OD ROZMOWY</span><h2>Twój plan.<br/>Nasze doświadczenie.</h2><p>Opisz, co chcesz zbudować lub zmienić. Dobry początek to jasny zakres, realny budżet i wspólnie ustalony plan.</p><div className="quote-steps"><div><b>01</b><span>Opisz inwestycję</span></div><div><b>02</b><span>Ustalmy zakres prac</span></div><div><b>03</b><span>Zaplanujmy realizację</span></div></div><div className="quote-contact"><span>KONTAKT DEMONSTRACYJNY</span><p>biuro@novabud.example<br/>+48 000 000 000</p><small>Przykładowe dane fikcyjnej firmy.</small></div></div>
    <div className="quote-card">{receipt ? <div className="success-panel" role="status"><Icon name="check" size={38}/><span className="eyebrow">PODSUMOWANIE DEMONSTRACYJNE</span><h3>{receipt.name}, Twoje zapytanie jest gotowe.</h3><dl><div><dt>Numer</dt><dd>{receipt.reference}</dd></div><div><dt>Usługa</dt><dd>{receipt.service}</dd></div><div><dt>Lokalizacja</dt><dd>{receipt.city}</dd></div>{receipt.area && <div><dt>Powierzchnia</dt><dd>{receipt.area} m²</dd></div>}<div><dt>Budżet</dt><dd>{receipt.budget}</dd></div></dl><p>Formularz został sprawdzony. To demonstracja — zapytanie nie zostało wysłane do firmy budowlanej.</p><button className="button button-navy" onClick={() => setReceipt(null)}>Przygotuj kolejne zapytanie</button><a href="/#/zamow" className="quote-real-link">Zamów podobną stronę w ProjektKreator.pl ↗</a></div> : <form onSubmit={submit}><h3>Opowiedz o inwestycji</h3><p className="form-note">Przetestuj formularz wyceny. Dane posłużą tylko do wyświetlenia podsumowania na tej stronie.</p><div className="form-grid"><label className="wide">Rodzaj prac<select name="service" required value={service} onChange={e => setService(e.target.value)}>{services.map(s => <option key={s.name}>{s.name}</option>)}</select></label><label>Imię i nazwisko<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Jan Kowalski"/></label><label>E-mail<input type="email" name="email" autoComplete="email" required maxLength={254} placeholder="jan@email.pl"/></label><label>Telefon (opcjonalnie)<input type="tel" name="phone" autoComplete="tel" maxLength={20} placeholder="+48 …"/></label><label>Miejscowość inwestycji<input name="city" required minLength={2} maxLength={100} placeholder="np. Katowice"/></label><label>Powierzchnia w m² (opcjonalnie)<input type="number" name="area" min="1" max="10000" step="1" placeholder="np. 120"/></label><label>Orientacyjny budżet<select name="budget" defaultValue="Do ustalenia"><option>Do ustalenia</option><option>Do 50 000 PLN</option><option>50 000–150 000 PLN</option><option>150 000–400 000 PLN</option><option>Powyżej 400 000 PLN</option></select></label><label className="wide">Co planujesz?<textarea name="description" required minLength={20} maxLength={3000} placeholder="Opisz zakres, etap inwestycji i planowany termin…"/></label></div><label className="consent"><input type="checkbox" required/>Rozumiem, że korzystam z formularza demonstracyjnego.</label>{error && <p role="alert" className="form-error">{error}</p>}<button className="button button-yellow" type="submit">Przygotuj zapytanie o wycenę <Icon name="arrow"/></button></form>}</div>
    </div></section>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState('Wszystkie');
  const [project, setProject] = useState(null);
  const [service, setService] = useState(services[0].name);
  function quote(value) { setService(value); document.getElementById('wycena')?.scrollIntoView(); }
  return <><a className="skip-link" href="#uslugi">Przejdź do usług</a><DemoBar name="NovaBud"/><header className="nova-header"><a className="nova-logo" href={import.meta.env.BASE_URL}><span className="nova-symbol"><Icon name="house" size={27}/></span>Nova<span>Bud</span><small>BUDUJEMY ZAUFANIE</small></a><nav className={menuOpen ? 'nav-open' : ''} aria-label="Nawigacja główna">{[['Usługi','#uslugi'],['Realizacje','#realizacje'],['O nas','#o-nas'],['Opinie','#opinie'],['Kontakt','#kontakt']].map(([label,href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><a className="button button-yellow header-quote" href="#wycena">Zapytaj o wycenę <Icon name="arrow" size={16}/></a><button className="icon-button mobile-menu-button" aria-label="Menu nawigacji" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><Icon name="menu"/></button></header>
    <main><section className="nova-hero"><div className="container nova-hero-grid"><div className="nova-hero-copy"><span className="eyebrow">BUDOWA · REMONT · WYKOŃCZENIE</span><h1>Solidny fundament.<br/><span>Dobry dom.</span></h1><p>Budujemy i remontujemy z myślą o tym, co ważne: jakości, terminach i Twoim spokoju.</p><div className="nova-hero-buttons"><a className="button button-yellow" href="#wycena">Porozmawiajmy o Twoim projekcie <Icon name="arrow"/></a><a className="hero-second-link" href="#realizacje">Zobacz realizacje ↗</a></div><div className="hero-trust"><Icon name="shield"/><span>Jasny zakres. Przejrzysty plan.<br/><b>Odpowiedzialność na każdym etapie.</b></span></div></div><div className="nova-hero-photo"><img src={imagePath('house')} alt="Nowoczesny dom z dużymi przeszkleniami, przykład architektury mieszkaniowej" width="1000" height="1100" fetchPriority="high"/><div className="project-label"><span>PRZYKŁADOWA REALIZACJA</span><strong>Dom pod lasem</strong><small>180 m² · Katowice</small><a href="#realizacje" aria-label="Zobacz projekt Dom pod lasem"><Icon name="arrow"/></a></div></div></div></section>
    <section className="nova-stats container" aria-label="Przykładowe dane firmy"><div><b>15<span>+</span></b><p>lat doświadczenia</p></div><div><b>120<span>+</span></b><p>zrealizowanych projektów</p></div><div><b>24</b><p>specjalistów w zespole</p></div><div><b>1</b><p>partner do całej inwestycji</p></div><small>Dane przykładowe dla demonstracji strony.</small></section>
    <section className="container section" id="uslugi"><div className="section-heading"><div><span className="eyebrow">ZAKRES, NA KTÓRYM MOŻESZ POLEGAĆ</span><h2>Od planu<br/>do ostatniego detalu.</h2></div><p>Wybierz usługę i opowiedz nam,<br/>czego potrzebuje Twoja inwestycja.</p></div><div className="service-grid">{services.map((s,i) => <article key={s.name}><div className="service-top"><Icon name={s.icon} size={32}/><span>0{i + 1}</span></div><h3>{s.name}</h3><p>{s.text}</p><ul>{s.points.map(point => <li key={point}><Icon name="check" size={16}/>{point}</li>)}</ul><button onClick={() => quote(s.name)}>Zapytaj o {s.name.toLowerCase()} <Icon name="arrow" size={18}/></button></article>)}</div></section>
    <section className="projects-section section" id="realizacje"><div className="container"><div className="section-heading"><div><span className="eyebrow">EFEKTY MÓWIĄ SAME ZA SIEBIE</span><h2>Przestrzenie<br/>z dobrym początkiem.</h2></div><div className="project-filters" aria-label="Filtr realizacji">{['Wszystkie','Domy','Wnętrza'].map(f => <button key={f} className={filter === f ? 'active' : ''} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f}</button>)}</div></div><div className="projects-grid">{projects.filter(p => filter === 'Wszystkie' || p.category === filter).map(p => <button className="nova-project" key={p.name} onClick={() => setProject(p)} aria-label={`Otwórz realizację: ${p.name}`}><div><img src={imagePath(p.image)} alt={p.name} loading="lazy" width="800" height="700"/><span>{p.category}</span></div><div className="nova-project-info"><span>{p.location} · {p.area} · {p.year}</span><h3>{p.name}</h3><Icon name="arrow"/></div></button>)}</div><p className="sample-caption">Galeria prezentuje przykładowe projekty i fotografie architektury.</p></div></section>
    <section className="container section about-section" id="o-nas"><div className="about-image"><img src={imagePath('build')} alt="Planowanie prac i analiza rysunków architektonicznych" width="1000" height="850" loading="lazy"/><div><b>Dobry projekt</b><span>zaczyna się od rozmowy.</span></div></div><div><span className="eyebrow">POZNAJ NOVABUD</span><h2>Za każdą realizacją<br/>stoi zgrany zespół.</h2><p>Łączymy praktyczne doświadczenie z dobrą organizacją. Słuchamy, planujemy i jasno ustalamy zasady współpracy, zanim rozpoczniemy prace.</p><p>Jedna osoba do kontaktu, uporządkowany harmonogram i regularne informacje o postępach. Tak rozumiemy spokojną budowę.</p><div className="about-checks"><span><Icon name="check"/> Przejrzysty zakres prac</span><span><Icon name="check"/> Ustalony harmonogram</span><span><Icon name="check"/> Dbałość o szczegóły</span></div><a className="button button-navy" href="#wycena">Poznajmy Twój projekt <Icon name="arrow"/></a></div></section>
    <section className="testimonials-section section" id="opinie"><div className="container"><div className="section-heading"><div><span className="eyebrow">WSPÓŁPRACA, KTÓRA ZOSTAJE W PAMIĘCI</span><h2>Nie tylko budynki.<br/>Także relacje.</h2></div><p>Przykładowe opinie<br/>na potrzeby demonstracji.</p></div><div className="testimonials">{[['Anna K.','Remont mieszkania','Jasny plan od pierwszego spotkania. Wiedziałam, co jest robione i jaki będzie następny etap.'],['Michał P.','Budowa domu','Doceniam rzeczowy kontakt i uwagę poświęconą szczegółom. Cały proces był dla nas zrozumiały.'],['Karolina i Piotr','Wykończenie wnętrz','Pomogli nam poukładać decyzje i połączyć estetykę z codzienną wygodą.']].map(([name,type,text]) => <figure key={name}><div className="quote-mark">“</div><blockquote>{text}</blockquote><figcaption><span className="avatar">{name[0]}</span><span><b>{name}</b><small>{type} · opinia przykładowa</small></span></figcaption></figure>)}</div></div></section>
    <QuoteForm service={service} setService={setService}/>
    <section className="container contact-section" id="kontakt"><div><Icon name="pin"/><h3>Obszar działania</h3><p>Katowice i województwo śląskie<br/><small>Przykładowy obszar obsługi</small></p></div><div><Icon name="clock"/><h3>Porozmawiajmy</h3><p>Poniedziałek–piątek: 8:00–17:00<br/>Sobota: po wcześniejszym ustaleniu</p></div><div><Icon name="arrow"/><h3>Chcesz podobną stronę?</h3><p><a href="/#/kontakt">Skontaktuj się z ProjektKreator.pl</a><br/>Strona przygotowana jako portfolio.</p></div></section></main>
    <footer className="site-footer nova-footer"><div className="container"><div className="footer-grid"><div><a className="nova-logo" href={import.meta.env.BASE_URL}>Nova<span>Bud</span></a><p>Solidny fundament. Dobry dom.</p></div><div><h3>POZNAJ NAS</h3><a href="#uslugi">Usługi</a><a href="#realizacje">Realizacje</a><a href="#o-nas">O nas</a></div><div><h3>TWÓJ PROJEKT</h3><a href="#wycena">Formularz wyceny</a><a href="#kontakt">Kontakt</a><a href="/">ProjektKreator.pl</a></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} NovaBud · Fikcyjna firma. Strona demonstracyjna ProjektKreator.pl.</p><p>Przykładowe dane, projekty i opinie.</p></div></div></footer>
    {project && <Modal title={project.name} onClose={() => setProject(null)} className="lightbox"><img src={imagePath(project.image)} alt={project.name}/><span className="eyebrow project-modal-eyebrow">{project.location} · {project.area} · {project.year}</span><h2>{project.name}</h2><p>{project.text}</p><button className="button button-navy" onClick={() => { setProject(null); quote(project.category === 'Domy' ? 'Budowa domów' : 'Wykończenia wnętrz'); }}>Zapytaj o podobny zakres <Icon name="arrow"/></button></Modal>}
  </>;
}
