services:
  - type: web
    name: projektkreator-pl
    runtime: node
    plan: free
    buildCommand: echo "No build required"
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
