export const products = [
  { id: 'jacket', name: 'Kurtka Everyday', category: 'Kurtki', price: 329, image: 'jacket', color: 'Oliwkowy', sizes: ['S', 'M', 'L', 'XL'], description: 'Lekka kurtka o swobodnym kroju. Praktyczne kieszenie i wygodne zapięcie sprawdzą się w codziennych stylizacjach.', material: 'Bawełniana tkanina z podszewką', badge: 'Bestseller' },
  { id: 'shirt', name: 'Koszula Essential', category: 'Koszule', price: 189, image: 'shirt', color: 'Jasny', sizes: ['XS', 'S', 'M', 'L'], description: 'Ponadczasowy fason, który pasuje do jeansów i eleganckich spodni. Noś luźno albo z podwiniętym rękawem.', material: 'Lekka, przewiewna tkanina', badge: 'Nowość' },
  { id: 'jeans', name: 'Jeansy Original', category: 'Jeans', price: 249, image: 'jeans', color: 'Niebieski denim', sizes: ['XS', 'S', 'M', 'L', 'XL'], description: 'Ulubiony denim na wiele sezonów. Klasyczne kieszenie, wygodny stan i prosty krój nogawki.', material: 'Denim bawełniany', badge: '' },
  { id: 'bag', name: 'Torebka City', category: 'Dodatki', price: 279, image: 'bag', color: 'Kolor ze zdjęcia', sizes: ['ONE'], description: 'Wyrazisty dodatek z miejscem na codzienne drobiazgi. Do pracy, na spacer i na wieczorne wyjście.', material: 'Materiał o skórzanej fakturze', badge: 'Nasza selekcja' },
  { id: 'dress', name: 'Sukienka Weekend', category: 'Sukienki', price: 299, image: 'dress', color: 'Kolor ze zdjęcia', sizes: ['XS', 'S', 'M', 'L'], description: 'Lekki, kobiecy fason, który nie potrzebuje wielu dodatków. Wygoda na co dzień i na wyjątkowe okazje.', material: 'Miękka tkanina o lekkim splocie', badge: 'Nowość' },
  { id: 'knit', name: 'T-shirt Daily', category: 'T-shirty', price: 99, image: 'knit', color: 'Kolor ze zdjęcia', sizes: ['S', 'M', 'L', 'XL'], description: 'Prosty T-shirt do codziennych zestawów. Miękki materiał, wygodny dekolt i swobodny fason.', material: 'Bawełniana dzianina', badge: '' },
];
export const categories = ['Wszystko', ...new Set(products.map(product => product.category))];
