import React,{useEffect,useState} from 'react';
import {assets} from './assets';
import './styles.css';

const nav=[['services','Usługi'],['portfolio','Nasze realizacje'],['pricing','Cennik'],['contact','Napisz do nas']];

function Logo({go}){return <button className="logo" onClick={()=>go('services')}><span className="logoLeaf"><i/><i/></span><span><b>ProjektKreator.pl</b><small>STRONY • SKLEPY • APLIKACJE</small></span></button>}
function Header({page,go}){const[open,setOpen]=useState(false);return <header><div className="shell nav"><Logo go={go}/><button className="hamb" onClick={()=>setOpen(!open)} aria-label="Menu">☰</button><nav className={open?'open':''}>{nav.map(([k,v])=><button key={k} className={page===k?'active':''} onClick={()=>{go(k);setOpen(false)}}>{v}</button>)}</nav><button className="pill navCta" onClick={()=>go('contact')}>Rozpocznij projekt →</button></div></header>}
function Footer({go}){return <footer><div className="shell footer"><Logo go={go}/><div className="footerLinks">{nav.map(([k,v])=><button key={k} onClick={()=>go(k)}>{v}</button>)}</div><div className="social">● ◎ in ▶</div></div></footer>}
function Hero({variant='',eyebrow,title,text,image,children}){return <section className={'hero '+variant}><div className="shell heroGrid"><div className="heroCopy"><div className="eyebrow">{eyebrow}</div><h1 dangerouslySetInnerHTML={{__html:title}}/><p>{text}</p>{children}</div><div className="heroMedia"><img src={image} alt=""/></div></div></section>}
function Stats({items}){return <div className="stats">{items.map(([icon,value,label])=><div className="stat" key={value}><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div>)}</div>}
function CTA({go,title,text}){return <section className="cta"><div className="shell ctaGrid"><div><div className="eyebrow">Porozmawiajmy o projekcie</div><h2>{title}</h2><p>{text}</p></div><button className="pill" onClick={()=>go('contact')}>Rozpocznij projekt →</button></div></section>}

const services=[
 ['web','service_web','Strony internetowe','Nowoczesne strony, które budują zaufanie i dobrze wyglądają na każdym urządzeniu.','od 1 499 PLN'],
 ['web','service_shop','Sklepy online','Sklepy z płatnościami, dostawą, produktami i prostą obsługą dla właściciela.','od 2 499 PLN'],
 ['apps','service_app','Aplikacje webowe','Dedykowane systemy i panele dopasowane do procesów Twojej firmy.','od 3 999 PLN'],
 ['support','service_debug','Debug i poprawki','Poprawki błędów, optymalizacja i rozwój istniejących stron oraz aplikacji.','od 199 PLN'],
 ['support','service_qa','Testowanie QA','Testy funkcjonalne, UX i responsywności przed publikacją projektu.','od 699 PLN'],
 ['design','service_brand','Logo i identyfikacja','Logo, kolory i spójny kierunek wizualny dla Twojej marki.','od 1 199 PLN'],
 ['ai','service_ai','AI i automatyzacje','Automatyzacje i funkcje AI, które oszczędzają czas i usprawniają pracę.','od 1 499 PLN']
];
const filters=[['all','Wszystkie usługi'],['web','Strony i sklepy'],['apps','Aplikacje i systemy'],['support','Wsparcie techniczne'],['design','Projektowanie'],['ai','Automatyzacje']];
function Services({go}){const[f,setF]=useState('all');return <>
 <Hero variant="servicesHero" eyebrow="Nasze usługi" title={'Usługi dopasowane<br/>do Twojego biznesu.'} text="Tworzymy nowoczesne rozwiązania od pomysłu, przez projekt i wdrożenie, aż po wsparcie po starcie." image={assets.hero_services}><Stats items={[["▣","100+","zrealizowanych projektów"],["♡","98%","zadowolonych klientów"],["◫","3+ lata","doświadczenia"]]}/></Hero>
 <div className="shell filters">{filters.map(([k,v])=><button key={k} className={f===k?'active':''} onClick={()=>setF(k)}>{v}</button>)}</div>
 <section className="section compact"><div className="shell serviceGrid">{services.filter(s=>f==='all'||s[0]===f).map(s=><article className="serviceCard" key={s[2]}><div className="serviceImage"><img src={assets[s[1]]} alt=""/></div><div className="serviceBody"><h3>{s[2]}</h3><p>{s[3]}</p><div className="serviceBottom"><strong>{s[4]}</strong><span>→</span></div></div></article>)}<article className="serviceCard help"><div className="serviceBody"><div className="eyebrow">Pomoc w wyborze</div><h2>Nie wiesz, czego potrzebujesz?</h2><p>Opowiedz nam o celu. Dobierzemy rozwiązanie bez zbędnych funkcji.</p><button className="pill" onClick={()=>go('contact')}>Napisz do nas →</button></div></article></div></section>
 <section className="section tint"><div className="shell processGrid"><div><div className="eyebrow">Jak to działa?</div><h2>Od pomysłu do efektu w 4 krokach.</h2></div>{[['01','Rozmowa i analiza','Poznajemy potrzeby i cel biznesowy.'],['02','Projekt i wycena','Ustalamy zakres, design i harmonogram.'],['03','Realizacja','Tworzymy, testujemy i wdrażamy.'],['04','Wsparcie','Pomagamy po publikacji i rozwijamy projekt.']].map(x=><div className="processStep" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></section>
 <section className="section"><div className="shell benefitsGrid"><div><div className="eyebrow">Dlaczego warto?</div><h2>Więcej niż samo wykonanie strony.</h2></div>{[['◇','Indywidualne podejście','Projekt dopasowany do marki i klientów.'],['↗','Praktyczny design','Estetyka połączona z funkcjonalnością.'],['◈','Jasny proces','Czytelny zakres i kolejne etapy.'],['♡','Wsparcie','Pomoc po starcie projektu.']].map(x=><div className="benefit" key={x[1]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></section>
 <CTA go={go} title="Masz pomysł? Zmieńmy go w gotowy produkt." text="Napisz do nas i otrzymaj dopasowaną propozycję."/>
 </>}

const demoData={
 modea:{name:'MODÉA',kicker:'SKLEP MODOWY',title:'Styl, który podkreśla Ciebie.',accent:'#9a5b85',soft:'#f7edf3',cards:['Nowa kolekcja','Bestsellery','Lookbook'],metric:'180% wzrost sprzedaży'},
 novabud:{name:'NovaBud',kicker:'BUDOWNICTWO',title:'Budujemy lepsze jutro.',accent:'#43524c',soft:'#edf2ef',cards:['Domy','Realizacje','Wycena'],metric:'12 lat doświadczenia'},
 greenlife:{name:'GreenLife',kicker:'NATURALNY SKLEP',title:'Naturalne piękno na co dzień.',accent:'#5f7b64',soft:'#eef5ed',cards:['Pielęgnacja','Składniki','Nowości'],metric:'100% naturalnie'},
 fitzone:{name:'FitZone',kicker:'APLIKACJA FITNESS',title:'Lepsza wersja Ciebie zaczyna się dziś.',accent:'#345f9e',soft:'#edf2fb',cards:['Plany','Postępy','Trener'],metric:'120+ treningów'}
};
function HtmlDemo({kind,large=false}){const d=demoData[kind];return <div className={'htmlDemo '+kind+(large?' large':'')} style={{'--demoAccent':d.accent,'--demoSoft':d.soft}}>
 <div className="demoHeader"><b>{d.name}</b><div><span>Start</span><span>Oferta</span><span>O nas</span></div><button>Kontakt</button></div>
 <div className="demoHeroHtml"><div className="demoHeroText"><small>{d.kicker}</small><h4>{d.title}</h4><p>Nowoczesny projekt z czytelną strukturą, mocnym nagłówkiem i sekcjami dopasowanymi do marki.</p><button>Zobacz więcej →</button></div><div className="demoArt"><div className="artPanel"><i/><i/><i/></div><div className="artBadge">{d.metric}</div></div></div>
 <div className="demoCards">{d.cards.map((c,i)=><div key={c}><small>0{i+1}</small><b>{c}</b><span>Przejrzysta sekcja</span></div>)}</div>
 <div className="demoFooterStrip"><b>{kind==='modea'?'Moda. Jakość. Pewność.':kind==='novabud'?'Projekt. Budowa. Efekt.':kind==='greenlife'?'Prosty skład. Dobry wybór.':'Plan. Ruch. Wynik.'}</b><span>projekt demonstracyjny</span></div>
 </div>}
function DemoModal({kind,onClose}){useEffect(()=>{const h=e=>e.key==='Escape'&&onClose();addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[onClose]);return <div className="modal" onClick={onClose}><div className="modalBox" onClick={e=>e.stopPropagation()}><div className="browser"><i/><i/><i/><span>{kind}.projektkreator-demo.pl</span><button onClick={onClose}>×</button></div><HtmlDemo kind={kind} large/></div></div>}
const projects=[['modea','MODÉA','Sklep internetowy','Elegancki sklep z kolekcjami, produktami i lekkim layoutem.'],['novabud','NovaBud','Strona firmowa','Profesjonalna prezentacja usług, realizacji i procesu współpracy.'],['greenlife','GreenLife','Sklep internetowy','Naturalna estetyka, produkty i spokojna ścieżka zakupowa.'],['fitzone','FitZone','Aplikacja webowa','Panel treningowy z planami, postępami i profilem użytkownika.']];
function Portfolio({go}){const[demo,setDemo]=useState(null);return <>
 <Hero variant="portfolioHero" eyebrow="Nasze realizacje" title={'Zobacz projekty,<br/>które już działają.'} text="Pokazujemy układ, design i sposób działania — nie same zdjęcia." image={assets.hero_portfolio}><Stats items={[["▣","100+","zrealizowanych projektów"],["♡","98%","zadowolonych klientów"],["↗","Różne branże","od firm lokalnych po marki online"]]}/></Hero>
 <section className="section tint"><div className="shell"><div className="eyebrow">Wyróżniona realizacja</div><div className="featured"><div className="featuredDemo"><div className="browser"><i/><i/><i/><span>modea.pl</span></div><HtmlDemo kind="modea" large/></div><div className="featuredCopy"><h2>MODÉA</h2><h4>Sklep internetowy z odzieżą damską</h4><p>Pełny interfejs demonstracyjny zbudowany z prawdziwych elementów HTML/React — nawigacji, hero, kart, przycisków i sekcji treści.</p><div className="featurePoints"><div><b>◎ Cel biznesowy</b><small>Lepsza prezentacja marki i sprzedaż online.</small></div><div><b>⚙ Zakres prac</b><small>Design, sklep, mobile i wdrożenie.</small></div><div><b>↗ Efekt</b><small>Spójny, czytelny interfejs.</small></div></div><button className="pill" onClick={()=>setDemo('modea')}>Otwórz demo →</button></div></div></div></section>
 <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Nasze projekty</div><h2>Cztery różne branże. Cztery realne interfejsy.</h2></div><p>Każde demo poniżej jest zbudowane z HTML/React i CSS, a nie z jednego obrazka.</p></div><div className="demoGrid">{projects.map(p=><article className="demoCard" key={p[0]}><div className="demoPreview"><HtmlDemo kind={p[0]}/></div><div className="demoCardText"><h3>{p[1]}</h3><b>{p[2]}</b><p>{p[3]}</p><button onClick={()=>setDemo(p[0])}>Zobacz pełne demo →</button></div></article>)}</div></div></section>
 <section className="trustBand"><div className="shell trustGrid"><div><div className="eyebrow">Zaufali nam</div><div className="logos"><span>MODÉA</span><span>NovaBud</span><span>GreenLife</span><span>FitZone</span></div></div><div className="trustNumbers"><b>98%<small>klientów poleca</small></b><b>100+<small>projektów</small></b></div></div></section>
 <section className="section reviews"><div className="shell reviewGrid"><div><div className="eyebrow">Co mówią klienci</div><h2>Zaufanie jest najlepszą rekomendacją.</h2></div><Review text="Profesjonalne podejście, świetny kontakt i bardzo dobry efekt końcowy." name="Anna Kowalska" brand="MODÉA"/><Review text="Projekt został dobrze przemyślany i przygotowany pod nasze potrzeby." name="Michał Nowak" brand="NovaBud"/><Review text="Szybka współpraca, dobry design i bardzo czytelny proces." name="Katarzyna Zielińska" brand="GreenLife"/></div></section>
 <CTA go={go} title="Twój projekt może być następny." text="Pokaż nam pomysł, a przygotujemy kierunek projektu."/>{demo&&<DemoModal kind={demo} onClose={()=>setDemo(null)}/>}</>}
function Review({text,name,brand}){return <blockquote><span>“</span><p>{text}</p><div><i>{name.split(' ').map(x=>x[0]).join('')}</i><b>{name}<small>{brand}</small></b></div></blockquote>}

const packs=[['Strona Start','599 PLN',['do 5 podstron','responsywność','formularz','podstawowe SEO']],['Strona Biznes','1 499 PLN',['do 15 podstron','indywidualny projekt','integracje','SEO']],['Strona Premium','2 499 PLN',['rozbudowany projekt','identyfikacja wizualna','integracje','wsparcie']],['Sklep internetowy','2 499 PLN',['płatności','produkty','dostawa','szkolenie']],['Aplikacja webowa','3 999 PLN',['indywidualne funkcje','integracje','testy','wdrożenie']]];
function Pricing({go}){return <><Hero variant="pricingHero" eyebrow="Cennik" title={'Przejrzysty<br/>cennik usług.'} text="Jasne zasady, czytelny zakres i pakiety, które można dopasować do projektu." image={assets.hero_pricing}/><section className="section tint"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Pakiety</div><h2>Wybierz rozwiązanie dla siebie.</h2></div><p>Zakres zawsze możemy dopasować po krótkiej rozmowie.</p></div><div className="pricingGrid">{packs.map((p,i)=><article className={'price '+(i===2?'popular':'')} key={p[0]}>{i===2&&<em>NAJCZĘŚCIEJ WYBIERANY</em>}<h3>{p[0]}</h3><strong>od {p[1]}</strong><ul>{p[2].map(x=><li key={x}>✓ {x}</li>)}</ul><button className="pill" onClick={()=>go('contact')}>Wybieram →</button></article>)}</div></div></section><CTA go={go} title="Potrzebujesz innego zakresu?" text="Przygotujemy indywidualną wycenę."/></>}

function Contact(){const[sent,setSent]=useState(false);return <><Hero variant="contactHero" eyebrow="Napisz do nas" title={'Porozmawiajmy<br/>o Twoim projekcie.'} text="Opisz pomysł, a wrócimy z propozycją kolejnych kroków." image={assets.hero_contact}/><section className="section tint"><div className="shell contactGrid"><form onSubmit={e=>{e.preventDefault();setSent(true);e.currentTarget.reset()}}><div className="eyebrow">Formularz projektu</div><h2>Opowiedz nam, czego potrzebujesz.</h2><div className="formGrid"><label>Imię i nazwisko<input required/></label><label>E-mail<input required type="email"/></label><label>Telefon<input/></label><label>Rodzaj projektu<select defaultValue=""><option value="" disabled>Wybierz</option><option>Strona internetowa</option><option>Sklep online</option><option>Aplikacja webowa</option><option>AI i automatyzacje</option></select></label><label className="full">Wiadomość<textarea required/></label></div><button className="pill" type="submit">Wyślij wiadomość →</button>{sent&&<p className="success">Dziękujemy. Formularz został przyjęty w interfejsie.</p>}</form><aside><div className="eyebrow">Co dalej?</div><h2>Prosty proces bez chaosu.</h2>{['Potwierdzamy wiadomość','Analizujemy potrzeby','Przedstawiamy zakres','Zaczynamy realizację'].map((x,i)=><div className="after" key={x}><span>0{i+1}</span><b>{x}</b></div>)}</aside></div></section></>}

export default function App(){const initial=()=>{const h=location.hash.slice(1);return nav.some(x=>x[0]===h)?h:'services'};const[page,setPage]=useState(initial);const go=p=>{setPage(p);history.replaceState(null,'','#'+p);window.scrollTo({top:0,behavior:'instant'})};useEffect(()=>{const h=()=>setPage(initial());addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);return <><Header page={page} go={go}/><main>{page==='services'&&<Services go={go}/>} {page==='portfolio'&&<Portfolio go={go}/>} {page==='pricing'&&<Pricing go={go}/>} {page==='contact'&&<Contact/>}</main><Footer go={go}/></>}
