import React,{useEffect,useMemo,useState} from 'react';
import {assets} from './assets';
import './styles.css';

const nav=[['/uslugi','Usługi'],['/realizacje','Nasze realizacje'],['/cennik','Cennik'],['/kontakt','Napisz do nas']];

function useRoute(){
  const [path,setPath]=useState(window.location.pathname||'/');
  useEffect(()=>{const onPop=()=>setPath(window.location.pathname||'/');window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
  const go=(to)=>{if(window.location.pathname!==to){window.history.pushState({},'',to)}setPath(to);window.scrollTo({top:0,behavior:'instant'})};
  return [path,go];
}

function Brand({go}){return <button className="brand" onClick={()=>go('/')} aria-label="ProjektKreator.pl — strona główna"><span className="brandMark"><i/><i/></span><span><b>ProjektKreator.pl</b><small>STRONY • SKLEPY • APLIKACJE</small></span></button>}
function Header({path,go}){const[open,setOpen]=useState(false);return <header className="siteHeader"><div className="shell navRow"><Brand go={go}/><button className="menuBtn" onClick={()=>setOpen(!open)} aria-label="Otwórz menu">☰</button><nav className={open?'open':''}>{nav.map(([to,label])=><button key={to} className={path===to?'active':''} onClick={()=>{go(to);setOpen(false)}}>{label}</button>)}</nav><button className="primary navCta" onClick={()=>go('/kontakt')}>Rozpocznij projekt <span>→</span></button></div></header>}
function Footer({go}){return <footer><div className="shell footerGrid"><Brand go={go}/><div className="footerLinks">{nav.map(([to,label])=><button key={to} onClick={()=>go(to)}>{label}</button>)}</div><p>Projektujemy strony, sklepy i aplikacje dla firm, które chcą wyglądać profesjonalnie online.</p></div><div className="shell footerBottom"><span>© ProjektKreator.pl</span><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Wróć na górę ↑</button></div></footer>}

function Eyebrow({children}){return <div className="eyebrow">{children}</div>}
function Hero({eyebrow,title,text,image,actions,children,compact=false}){return <section className={'hero '+(compact?'heroCompact':'')}><div className="shell heroGrid"><div className="heroCopy"><Eyebrow>{eyebrow}</Eyebrow><h1 dangerouslySetInnerHTML={{__html:title}}/><p className="heroLead">{text}</p>{actions&&<div className="heroActions">{actions}</div>}{children}</div><div className="heroVisual"><div className="heroFrame"><img src={image} alt=""/></div></div></div></section>}
function SectionHead({eyebrow,title,text,action}){return <div className="sectionHead"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div>{text&&<p>{text}</p>}{action}</div>}
function Pill({children,onClick,secondary=false}){return <button className={secondary?'secondary':'primary'} onClick={onClick}>{children}</button>}

const serviceItems=[
 ['01','Strony internetowe','Nowoczesne strony firmowe, landing pages i serwisy, które dobrze wyglądają i prowadzą klienta do działania.','od 599 PLN'],
 ['02','Sklepy online','Sklepy z czytelnym katalogiem, płatnościami, dostawą i wygodną obsługą produktów.','od 2 499 PLN'],
 ['03','Aplikacje webowe','Panele, narzędzia i dedykowane aplikacje dopasowane do procesu Twojej firmy.','od 3 999 PLN']
];

const projectMeta={
 modea:{name:'MODÉA',type:'Sklep internetowy',tag:'Styl w Twojej codzienności.',desc:'Kobiecy sklep modowy z kolekcjami, kartami produktów i spokojną, premium estetyką.'},
 novabud:{name:'NovaBud',type:'Strona firmowa',tag:'Budujemy lepsze jutro.',desc:'Strona firmy budowlanej z ofertą, realizacjami, procesem współpracy i wyceną.'},
 greenlife:{name:'GreenLife',type:'Sklep internetowy',tag:'Naturalne piękno na co dzień.',desc:'Sklep z naturalnymi kosmetykami z kategoriami produktów i lekkim, organicznym designem.'},
 fitzone:{name:'FitZone',type:'Aplikacja webowa',tag:'Plan. Ruch. Wynik.',desc:'Nowoczesna aplikacja treningowa z planem dnia, postępem i panelem użytkownika.'}
};

function MiniSite({kind}){const m=projectMeta[kind];return <div className={'miniSite mini-'+kind}>
 <div className="miniNav"><b>{m.name}</b><span>Start</span><span>Oferta</span><span>O nas</span><i/></div>
 <div className="miniHero"><div><small>{m.type}</small><h4>{m.tag}</h4><p>{kind==='modea'?'Nowa kolekcja stworzona na co dzień.':kind==='novabud'?'Od projektu do gotowego domu.':kind==='greenlife'?'Prosty skład. Dobry rytuał.':'Trening, który mieści się w Twoim planie.'}</p><u>{kind==='fitzone'?'Otwórz panel':'Zobacz więcej'} →</u></div><div className="miniArtwork">{kind==='modea'?<div className="fashionSilhouette"/>:kind==='novabud'?<div className="houseShape"/>:kind==='greenlife'?<div className="bottleGroup"/>:<div className="fitnessPanel"><span/><span/><span/></div>}</div></div>
 <div className="miniBottom"><span/><span/><span/></div>
 </div>}

function ProjectCard({kind,go}){const m=projectMeta[kind];return <article className="projectCard"><div className="projectPreview"><MiniSite kind={kind}/></div><div className="projectInfo"><div><small>{m.type}</small><h3>{m.name}</h3><p>{m.desc}</p></div><button onClick={()=>go('/demo/'+kind)}>Otwórz demo →</button></div></article>}

function Home({go}){return <>
 <Hero eyebrow="ProjektKreator.pl" title={'Twój pomysł.<br/>Nasza technologia.'} text="Tworzymy nowoczesne strony, sklepy i aplikacje, które pomagają firmom wyglądać profesjonalnie i zdobywać klientów online." image={assets.hero_services} actions={<><Pill onClick={()=>go('/kontakt')}>Zacznij projekt →</Pill><Pill secondary onClick={()=>go('/realizacje')}>Zobacz realizacje</Pill></>}><div className="heroProof"><span>Responsywny design</span><span>Jasna wycena</span><span>Wsparcie po wdrożeniu</span></div></Hero>
 <section className="section"><div className="shell"><SectionHead eyebrow="Co tworzymy" title="Strona ma nie tylko wyglądać. Ma pracować dla Twojego biznesu." text="Od prostych stron firmowych po sklepy i dedykowane narzędzia — projektujemy rozwiązania dopasowane do celu, nie do szablonu."/><div className="serviceTriptych">{serviceItems.map(([n,t,d,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><strong>{p}</strong></article>)}</div></div></section>
 <section className="section workSection"><div className="shell"><SectionHead eyebrow="Wybrane realizacje" title="Zobacz realne interfejsy, nie obrazki udające strony." text="Każde demo poniżej jest zbudowane w React/HTML. Możesz je otworzyć i zobaczyć prawdziwy układ strony." action={<button className="textLink" onClick={()=>go('/realizacje')}>Wszystkie realizacje →</button>}/><div className="projectGrid">{['modea','novabud','greenlife','fitzone'].map(k=><ProjectCard key={k} kind={k} go={go}/>)}</div></div></section>
 <section className="section splitSection"><div className="shell splitGrid"><div><Eyebrow>Jak pracujemy</Eyebrow><h2>Prosty proces bez chaosu.</h2><p>Najpierw ustalamy cel i zakres. Potem projektujemy, budujemy, testujemy i dopiero wtedy publikujemy.</p><Pill onClick={()=>go('/kontakt')}>Porozmawiajmy o projekcie →</Pill></div><div className="steps">{[['01','Rozmowa i cel','Krótko ustalamy czego potrzebujesz i dla kogo jest projekt.'],['02','Projekt i wycena','Dostajesz kierunek, zakres prac i jasną cenę.'],['03','Budowa i testy','Tworzymy wersję responsywną i sprawdzamy działanie.'],['04','Publikacja i wsparcie','Pomagamy uruchomić projekt i rozwijać go dalej.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></div>)}</div></div></section>
 <section className="section pricingPreview"><div className="shell"><SectionHead eyebrow="Cennik" title="Zacznij od zakresu, którego naprawdę potrzebujesz." text="Ceny startowe są widoczne od razu. Dokładną wycenę ustalamy po krótkiej rozmowie o projekcie."/><div className="pricePreviewGrid"><article><small>Strona Start</small><strong>od 599 PLN</strong><p>Dla małej firmy, usługi lokalnej lub prostego landing page.</p></article><article className="featuredPrice"><small>Strona Biznes</small><strong>od 1 499 PLN</strong><p>Rozbudowana strona z indywidualnym układem i większą liczbą sekcji.</p></article><article><small>Sklep online</small><strong>od 2 499 PLN</strong><p>Katalog, płatności, dostawa i przygotowanie do sprzedaży.</p></article></div><div className="centerAction"><Pill secondary onClick={()=>go('/cennik')}>Zobacz pełny cennik →</Pill></div></div></section>
 <section className="ctaBand"><div className="shell"><div><Eyebrow>Masz projekt?</Eyebrow><h2>Zróbmy stronę, którą możesz z dumą wysłać klientowi.</h2></div><Pill onClick={()=>go('/kontakt')}>Napisz do nas →</Pill></div></section>
 </>}

function Services({go}){return <><Hero compact eyebrow="Usługi" title={'Projektujemy cyfrowe narzędzia<br/>dla małych i rosnących firm.'} text="Strony, sklepy i aplikacje tworzymy jako jeden spójny produkt: design, technologia, mobile i wdrożenie." image={assets.service_web} actions={<Pill onClick={()=>go('/kontakt')}>Poproś o wycenę →</Pill>}/><section className="section"><div className="shell"><div className="servicesFull">{[
 ['01','Strony internetowe','Strony firmowe, landing pages, portfolio i serwisy usługowe.','Responsywny układ','Formularze i CTA','Podstawowe SEO','Wdrożenie'],
 ['02','Sklepy online','Sklepy dla marek, twórców i małych firm sprzedających online.','Katalog produktów','Płatności','Dostawa','Panel zarządzania'],
 ['03','Aplikacje webowe','Panele klienta, kalkulatory, systemy rezerwacji i dedykowane narzędzia.','Logowanie','Dashboard','Integracje','Automatyzacje'],
 ['04','Poprawki i rozwój','Naprawy, poprawa wyglądu, responsywności i rozwój istniejącej strony.','Debug','Mobile','UX','Aktualizacje']
 ].map(s=><article key={s[0]}><span>{s[0]}</span><div><h2>{s[1]}</h2><p>{s[2]}</p></div><ul>{s.slice(3).map(x=><li key={x}>✓ {x}</li>)}</ul></article>)}</div></div></section><section className="ctaBand"><div className="shell"><div><Eyebrow>Nie wiesz co wybrać?</Eyebrow><h2>Opisz cel. Dobierzemy zakres bez zbędnych funkcji.</h2></div><Pill onClick={()=>go('/kontakt')}>Napisz do nas →</Pill></div></section></>}

function Portfolio({go}){return <><Hero compact eyebrow="Nasze realizacje" title={'Cztery kierunki.<br/>Cztery realne demonstracje.'} text="Nie pokazujemy samych zdjęć. Każde demo ma własny układ, nawigację, sekcje i responsywną strukturę zbudowaną w React." image={assets.hero_portfolio}/><section className="section"><div className="shell"><div className="projectGrid projectGridLarge">{['modea','novabud','greenlife','fitzone'].map(k=><ProjectCard key={k} kind={k} go={go}/>)}</div></div></section><section className="section trustSection"><div className="shell trustLayout"><div><Eyebrow>Co pokazujemy klientowi</Eyebrow><h2>Design, który można naprawdę otworzyć i sprawdzić.</h2></div><div className="trustCards"><article><b>01</b><h3>Desktop</h3><p>Układ zaprojektowany pod laptop i duży ekran.</p></article><article><b>02</b><h3>Mobile</h3><p>Każde demo skaluje się do telefonu bez utraty czytelności.</p></article><article><b>03</b><h3>Interakcje</h3><p>Przyciski, sekcje, nawigacja i formularze są częścią prawdziwego UI.</p></article></div></div></section></>}

const pricing=[
 ['Strona Start','od 599 PLN',['do 5 sekcji','responsywny układ','formularz kontaktowy','podstawowe SEO']],
 ['Strona Biznes','od 1 499 PLN',['indywidualny układ','więcej sekcji/podstron','integracje formularzy','rozszerzone SEO']],
 ['Sklep internetowy','od 2 499 PLN',['katalog produktów','płatności','dostawa','panel sklepu']],
 ['Aplikacja webowa','od 3 999 PLN',['indywidualne funkcje','logowanie/panel','integracje','testy i wdrożenie']]
];
function Pricing({go}){return <><Hero compact eyebrow="Cennik" title={'Jasne ceny startowe.<br/>Zakres dopasowany do projektu.'} text="Nie sprzedajemy jednego szablonu każdej firmie. Cena zależy od funkcji, liczby widoków i integracji, ale punkt startowy znasz od razu." image={assets.hero_pricing}/><section className="section"><div className="shell pricingGrid">{pricing.map((p,i)=><article className={i===1?'recommended':''} key={p[0]}>{i===1&&<em>NAJCZĘŚCIEJ WYBIERANY</em>}<small>{p[0]}</small><strong>{p[1]}</strong><ul>{p[2].map(x=><li key={x}>✓ {x}</li>)}</ul><Pill onClick={()=>go('/kontakt')}>Zapytaj o projekt →</Pill></article>)}</div></section><section className="section faqSection"><div className="shell faqGrid"><div><Eyebrow>Najczęstsze pytania</Eyebrow><h2>Przed rozpoczęciem projektu.</h2></div><FAQ/></div></section></>}
function FAQ(){const items=[['Czy wycena jest darmowa?','Tak. Wstępny zakres i wycena mogą być przygotowane po krótkim opisie projektu.'],['Czy można płacić etapami?','Tak. Przy większych projektach możemy podzielić płatność zgodnie z etapami realizacji.'],['Czy strona będzie działać na telefonie?','Tak. Responsywność jest częścią projektu, nie dodatkiem.'],['Czy można później rozbudować stronę?','Tak. Projektujemy strukturę tak, aby dało się dodawać kolejne sekcje i funkcje.']];const[o,setO]=useState(0);return <div className="faq">{items.map((x,i)=><div key={x[0]}><button onClick={()=>setO(o===i?-1:i)}><span>{x[0]}</span><b>{o===i?'−':'+'}</b></button>{o===i&&<p>{x[1]}</p>}</div>)}</div>}

function Contact(){const[sent,setSent]=useState(false);return <><Hero compact eyebrow="Kontakt" title={'Opowiedz nam,<br/>co chcesz zbudować.'} text="Napisz krótko czego potrzebujesz. Formularz pomoże zebrać najważniejsze informacje do wstępnej wyceny." image={assets.hero_contact}/><section className="section"><div className="shell contactGrid"><form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="formRow"><label>Imię i nazwisko<input required name="name" placeholder="np. Anna Kowalska"/></label><label>E-mail<input required type="email" name="email" placeholder="np. anna@firma.pl"/></label></div><div className="formRow"><label>Rodzaj projektu<select required defaultValue=""><option value="" disabled>Wybierz</option><option>Strona internetowa</option><option>Sklep online</option><option>Aplikacja webowa</option><option>Poprawki istniejącej strony</option></select></label><label>Budżet<select defaultValue=""><option value="">Nie wiem jeszcze</option><option>do 1 000 PLN</option><option>1 000–3 000 PLN</option><option>3 000–7 000 PLN</option><option>powyżej 7 000 PLN</option></select></label></div><label>Opisz projekt<textarea required name="message" placeholder="Co ma robić strona? Dla jakiej firmy? Jakie funkcje są potrzebne?"/></label><button className="primary" type="submit">Wyślij zapytanie →</button>{sent&&<div className="formNotice">Formularz jest gotowy wizualnie. Następnym krokiem będzie podłączenie realnej wysyłki wiadomości.</div>}</form><aside><Eyebrow>Co dzieje się dalej?</Eyebrow><h2>Krótki, konkretny proces.</h2>{[['1','Czytamy opis','Sprawdzamy zakres i cel projektu.'],['2','Wracamy z pytaniami','Doprecyzowujemy funkcje i termin.'],['3','Dostajesz wycenę','Przed startem znasz zakres, cenę i kolejne kroki.']].map(x=><div className="contactStep" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></div>)}</aside></div></section></>}

function DemoLayout({kind,go}){const m=projectMeta[kind];const demo=kind==='modea'?<ModeaDemo/>:kind==='novabud'?<NovaBudDemo/>:kind==='greenlife'?<GreenLifeDemo/>:<FitZoneDemo/>;return <div className="demoPage"><div className="demoToolbar"><button onClick={()=>go('/realizacje')}>← Wróć do realizacji</button><div><b>{m.name}</b><span>{m.type}</span></div><button onClick={()=>go('/kontakt')}>Chcę podobny projekt →</button></div>{demo}</div>}

function ModeaDemo(){return <div className="brandDemo modeaDemo"><nav><b>MODÉA</b><div><a>Nowości</a><a>Kobieta</a><a>Lookbook</a><a>O marce</a></div><button>Koszyk (0)</button></nav><section className="modeaHero"><div><small>NOWA KOLEKCJA</small><h1>Styl w Twojej codzienności.</h1><p>Spokojne formy, kobiece detale i ubrania stworzone do prawdziwego życia.</p><button>Odkryj kolekcję →</button></div><div className="modeaModel"><div className="modelShape"/></div></section><section className="demoProducts"><div className="demoSectionTitle"><span>01</span><h2>Wybrane z kolekcji</h2></div><div className="productGrid">{['Linen Set','Soft Blazer','Everyday Dress','Classic Shirt'].map((x,i)=><article key={x}><div className={'productArt art'+i}/><b>{x}</b><span>{[249,319,289,199][i]} PLN</span></article>)}</div></section><section className="modeaStatement"><p>MODÉA</p><h2>Moda, która podkreśla Ciebie — nie przykrywa.</h2></section></div>}
function NovaBudDemo(){return <div className="brandDemo novaDemo"><nav><b>NovaBud</b><div><a>Usługi</a><a>Realizacje</a><a>Proces</a><a>Kontakt</a></div><button>Bezpłatna wycena</button></nav><section className="novaHero"><div><small>BUDUJEMY OD PODSTAW</small><h1>Dom zaczyna się od dobrego planu.</h1><p>Kompleksowa realizacja inwestycji — od pierwszego szkicu do odbioru.</p><button>Zobacz realizacje →</button></div><div className="architecture"><span/><span/><span/></div></section><section className="novaStats"><div><b>01</b><span>Projekt</span></div><div><b>02</b><span>Budowa</span></div><div><b>03</b><span>Wykończenie</span></div><div><b>04</b><span>Odbiór</span></div></section><section className="demoProjects"><div className="demoSectionTitle"><span>Realizacje</span><h2>Budujemy rzeczy, które zostają na lata.</h2></div><div className="buildGrid"><article/><article/><article/></div></section></div>}
function GreenLifeDemo(){return <div className="brandDemo greenDemo"><nav><b>GreenLife</b><div><a>Sklep</a><a>Pielęgnacja</a><a>Składniki</a><a>O nas</a></div><button>Koszyk</button></nav><section className="greenHero"><div><small>NATURALNA PIELĘGNACJA</small><h1>Prosty skład. Dobry rytuał.</h1><p>Kosmetyki inspirowane naturą, stworzone do codziennej, spokojnej pielęgnacji.</p><button>Zobacz produkty →</button></div><div className="cosmeticScene"><i/><i/><i/></div></section><section className="greenCategories">{['Twarz','Ciało','Włosy'].map((x,i)=><article key={x}><div className={'leafArt leaf'+i}/><b>{x}</b><span>Odkryj kategorię →</span></article>)}</section><section className="greenNote"><span>100%</span><h2>Bez zbędnego hałasu. Tylko skład, który ma sens.</h2></section></div>}
function FitZoneDemo(){return <div className="brandDemo fitDemo"><nav><b>FitZone</b><div><a>Plan</a><a>Treningi</a><a>Postępy</a></div><button>Profil</button></nav><div className="fitShell"><aside><b>FZ</b><button className="active">Dzisiaj</button><button>Plan</button><button>Ćwiczenia</button><button>Postępy</button></aside><main><div className="fitWelcome"><div><small>DZIEŃ 12</small><h1>Twój plan na dziś.</h1><p>45 minut • całe ciało • poziom średni</p></div><button>Rozpocznij trening →</button></div><div className="fitCards"><article><span>Postęp tygodnia</span><b>4 / 5</b><div className="progress"><i/></div></article><article><span>Dzisiejszy trening</span><b>Full Body</b><small>8 ćwiczeń</small></article><article><span>Seria</span><b>12 dni</b><small>Najlepszy wynik</small></article></div><div className="fitChart"><h2>Aktywność</h2><div className="bars">{[42,72,55,88,64,78,92].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div></main></div></div>}

function NotFound({go}){return <section className="notFound"><h1>404</h1><p>Nie znaleźliśmy tej strony.</p><Pill onClick={()=>go('/')}>Wróć na stronę główną</Pill></section>}

export default function App(){const[path,go]=useRoute();const page=useMemo(()=>{if(path==='/')return <Home go={go}/>;if(path==='/uslugi')return <Services go={go}/>;if(path==='/realizacje')return <Portfolio go={go}/>;if(path==='/cennik')return <Pricing go={go}/>;if(path==='/kontakt')return <Contact/>;if(path.startsWith('/demo/')){const kind=path.split('/')[2];if(projectMeta[kind])return <DemoLayout kind={kind} go={go}/>;}return <NotFound go={go}/>},[path]);const isDemo=path.startsWith('/demo/');return <>{!isDemo&&<Header path={path} go={go}/>}<main>{page}</main>{!isDemo&&<Footer go={go}/>}</>}
