import React,{useEffect,useState} from 'react';
import {assets} from './assets';
import './styles.css';

const nav=[['services','Usługi'],['portfolio','Nasze realizacje'],['pricing','Cennik'],['contact','Napisz do nas']];

function Logo({go}){return <button className="logo" onClick={()=>go('services')}><span className="logoMark">◆</span><span><b>ProjektKreator.pl</b><small>STRONY • SKLEPY • APLIKACJE</small></span></button>}
function Header({page,go}){const[o,setO]=useState(false);return <header><div className="wrap nav"><Logo go={go}/><button className="hamb" onClick={()=>setO(!o)}>☰</button><nav className={o?'open':''}>{nav.map(([k,v])=><button key={k} className={page===k?'active':''} onClick={()=>{go(k);setO(false)}}>{v}</button>)}</nav><button className="pill" onClick={()=>go('contact')}>Rozpocznij projekt →</button></div></header>}
function Footer({go}){return <footer><div className="wrap footer"><Logo go={go}/><div className="footerNav">{nav.map(([k,v])=><button key={k} onClick={()=>go(k)}>{v}</button>)}</div><div className="social">● ◎ in ▶</div></div></footer>}
function Hero({eyebrow,title,text,image,children,focus='center'}){return <section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow">{eyebrow}</div><h1 dangerouslySetInnerHTML={{__html:title}}/><p>{text}</p>{children}</div><div className="heroImage"><img src={image} style={{objectPosition:focus}}/></div></div></section>}
function Stats({items}){return <div className="stats">{items.map(([i,v,l])=><div className="stat" key={v}><span>{i}</span><div><b>{v}</b><small>{l}</small></div></div>)}</div>}
function CTA({go,eyebrow,title,text,button='Rozpocznij projekt →'}){return <section className="cta"><div className="wrap ctaGrid"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2><p>{text}</p></div><button className="pill" onClick={()=>go('contact')}>{button}</button></div></section>}

const services=[
 ['web','service_web','Strony internetowe','Nowoczesne strony www, które budują zaufanie i przyciągają klientów. Dopasowane do Twojej branży i urządzeń mobilnych.','Już od 1 499 PLN'],
 ['web','service_shop','Sklepy online','Skuteczne sklepy internetowe, które sprzedają. Integracje z płatnościami, wysyłkami i systemami magazynowymi.','Już od 2 499 PLN'],
 ['apps','service_app','Aplikacje webowe','Dedykowane rozwiązania webowe dopasowane do Twoich procesów. Większe możliwości dla Twojego biznesu.','Już od 3 999 PLN'],
 ['support','service_debug','Debug i poprawki','Szybka pomoc w rozwiązywaniu problemów, poprawki błędów i rozwój istniejących projektów.','Już od 199 PLN'],
 ['support','service_qa','Testowanie QA','Kompleksowe testy funkcjonalne, wydajnościowe i UX. Zadbamy o to, aby wszystko działało bez zarzutu.','Już od 699 PLN'],
 ['design','service_brand','Logo i identyfikacja','Unikalna identyfikacja wizualna, która wyróżni Twoją markę. Logo, kolorystyka, materiały i spójny wizerunek.','Już od 1 199 PLN'],
 ['ai','service_ai','AI i automatyzacje','Nowoczesne technologie AI i automatyzacje, które oszczędzają czas i zwiększają efektywność Twojej firmy.','Już od 1 499 PLN']
];
const filterNames=[['all','Wszystkie usługi'],['web','Strony i sklepy'],['apps','Aplikacje i systemy'],['support','Wsparcie techniczne'],['design','Projektowanie'],['ai','Automatyzacje']];
function Services({go}){const[f,setF]=useState('all');return <>
 <Hero eyebrow="Nasze usługi" title={'Usługi dopasowane<br/>do Twojego biznesu.'} text="Tworzymy nowoczesne rozwiązania, które wspierają rozwój Twojej marki w internecie. Od pomysłu, przez projekt, po wdrożenie i wsparcie — wszystko w jednym miejscu." image={assets.hero_services} focus="38% center"><Stats items={[["▣","100+","zrealizowanych projektów"],["♧","98%","zadowolonych klientów"],["▢","3+ lata","doświadczenia"]]}/></Hero>
 <div className="wrap filters">{filterNames.map(([k,v])=><button className={f===k?'active':''} onClick={()=>setF(k)} key={k}>{v}</button>)}</div>
 <section className="section compactTop"><div className="wrap cards4">{services.filter(s=>f==='all'||s[0]===f).map(s=><article className="card" key={s[2]}><img src={assets[s[1]]}/><div><h3>{s[2]}</h3><p>{s[3]}</p><strong>{s[4]}</strong><span className="arrow">→</span></div></article>)}<article className="card special"><div><h2>Nie wiesz,<br/>która usługa będzie najlepsza?</h2><p>Skontaktuj się z nami, a doradzimy najlepsze rozwiązanie dla Twojego biznesu.</p><button className="pill" onClick={()=>go('contact')}>Napisz do nas →</button></div></article></div></section>
 <section className="section tint"><div className="wrap steps"><div><div className="eyebrow">Jak to działa?</div><h2>Od pomysłu<br/>do efektu w 4 krokach.</h2></div>{[['01','Rozmowa i analiza','Poznajemy Twoje potrzeby i cele biznesowe.'],['02','Projekt i wycena','Przygotowujemy propozycję i plan działania.'],['03','Realizacja','Tworzymy, testujemy i wdrażamy rozwiązanie.'],['04','Wsparcie','Zapewniamy opiekę i rozwój projektu.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></section>
 <section className="section"><div className="wrap benefits"><div><div className="eyebrow">Dlaczego warto?</div><h2>Więcej niż tylko<br/>wykonanie projektu.</h2><p>Stawiamy na jakość, partnerską współpracę i realne efekty dla Twojego biznesu.</p></div>{[['◇','Indywidualne podejście','Każdy projekt dopasowujemy do Twoich celów.'],['↗','Doświadczenie i wiedza','Ponad 3 lata na rynku i setki zrealizowanych zadań.'],['◈','Terminowość i rzetelność','Działamy zgodnie z ustalonym harmonogramem.'],['♡','Wsparcie po wdrożeniu','Zapewniamy pomoc i rozwój.']].map(x=><div className="benefit" key={x[1]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></section>
 <CTA go={go} eyebrow="Porozmawiajmy o Twoim projekcie" title="Masz pomysł? Zmieńmy go w rzeczywistość." text="Skontaktuj się z nami i otrzymaj bezpłatną wycenę. Odpowiemy na wszystkie pytania i pomożemy dobrać najlepsze rozwiązanie."/>
 </>}

const demoMeta={
 modea:{name:'MODÉA',type:'Sklep internetowy',tag:'Moda, która podkreśla Ciebie.'},
 novabud:{name:'NovaBud',type:'Strona dla firmy budowlanej',tag:'Budujemy lepsze jutro.'},
 greenlife:{name:'GreenLife',type:'Sklep internetowy',tag:'Naturalne piękno na co dzień.'},
 fitzone:{name:'FitZone',type:'Aplikacja webowa',tag:'Lepsza wersja Ciebie zaczyna się dziś.'}
};
function DemoSite({kind,large=false}){const m=demoMeta[kind];const photo=kind==='modea'?assets.modea_woman:kind==='novabud'?assets.project_novabud:kind==='greenlife'?assets.project_greenlife:assets.project_fitzone;return <div className={'demoSite '+kind+(large?' large':'')}>
 <div className="demoTop"><b>{m.name}</b><span>Start</span><span>Oferta</span><span>O nas</span><button>{kind==='fitzone'?'Zacznij trening':'Dowiedz się więcej'}</button></div>
 <div className="demoHero"><div><small>{m.type}</small><h4>{m.tag}</h4><p>{kind==='modea'?'Elegancka kolekcja, spokojna paleta i zakupy stworzone wokół klientki.':kind==='novabud'?'Nowoczesne domy, przejrzysty proces i realizacje pokazane bez zbędnego chaosu.':kind==='greenlife'?'Naturalne kosmetyki, prosty skład i delikatna identyfikacja wizualna.':'Treningi, plany i wyniki w jednym miejscu.'}</p><button>{kind==='modea'?'Odkryj kolekcję':kind==='greenlife'?'Zobacz produkty':'Zobacz więcej'} →</button></div><img src={photo}/></div>
 <div className="demoStrip"><span>{kind==='novabud'?'12 lat doświadczenia':'01'}</span><span>{kind==='fitzone'?'120+ treningów':'02'}</span><span>{kind==='greenlife'?'100% naturalnie':'03'}</span></div>
 </div>}
function DemoModal({kind,onClose}){useEffect(()=>{const f=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[onClose]);return <div className="modal" onClick={onClose}><div className="modalBox" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="browserBar"><i/><i/><i/><span>demo.projektkreator.pl/{kind}</span></div><DemoSite kind={kind} large/></div></div>}

const projects=[
 ['modea','MODÉA','Sklep internetowy','Elegancki sklep modowy z wyrazistym hero i kolekcją dopasowaną do marki.'],
 ['novabud','NovaBud','Strona dla firmy budowlanej','Profesjonalna prezentacja realizacji, procesu i usług budowlanych.'],
 ['greenlife','GreenLife','Sklep internetowy','Naturalna estetyka, produkty i sprzedaż online w spójnym stylu.'],
 ['fitzone','FitZone','Aplikacja webowa','Platforma treningowa z czytelnym onboardingiem i panelami użytkownika.']
];
function Portfolio({go}){const[demo,setDemo]=useState(null);return <>
 <Hero eyebrow="Nasze realizacje" title={'Zobacz projekty,<br/>które już działają.'} text="Realne firmy, prawdziwe efekty. Poznaj nasze realizacje i przekonaj się, jak pomagamy markom rosnąć w świecie online." image={assets.hero_portfolio} focus="center"><Stats items={[["▣","100+","zrealizowanych projektów"],["♙","98%","zadowolonych klientów"],["↗","Różne branże","od lokalnych firm po ogólnopolskie marki"]]}/></Hero>
 <section className="section tint"><div className="wrap"><div className="eyebrow">Wyróżniona realizacja</div><div className="featured"><div className="featuredDemo"><div className="browserBar"><i/><i/><i/><span>modea.pl</span></div><DemoSite kind="modea" large/></div><div className="featuredCopy"><h2>MODÉA</h2><h4>Sklep internetowy z odzieżą damską</h4><p>Nowoczesny sklep internetowy, który łączy elegancki design z wygodnymi zakupami. Stworzyliśmy spójną identyfikację wizualną, wdrożyliśmy sklep i zadbaliśmy o pełne wsparcie techniczne.</p><div className="featurePoints"><div><b>◎ Cel biznesowy</b><small>Zwiększenie sprzedaży online i budowa rozpoznawalnej marki.</small></div><div><b>⚙ Zakres prac</b><small>Projekt graficzny, sklep, płatności i wdrożenie.</small></div><div><b>↗ Efekt</b><small>Gotowy sklep prezentowany jak prawdziwa marka.</small></div></div><button className="pill" onClick={()=>setDemo('modea')}>Zobacz całe demo →</button></div></div></div></section>
 <section className="section"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow">Nasze projekty</div><h2>Różne branże. Wspólny cel — rozwój.</h2></div><p>Każda karta poniżej pokazuje mini wersję realnego interfejsu, a nie samą fotografię.</p></div><div className="demoGrid">{projects.map(p=><article className="demoCard" key={p[0]}><DemoSite kind={p[0]}/><div className="demoCardText"><h3>{p[1]}</h3><b>{p[2]}</b><p>{p[3]}</p><button onClick={()=>setDemo(p[0])}>Zobacz pełne demo →</button></div></article>)}</div></div></section>
 <section className="trustBand"><div className="wrap trustGrid"><div><div className="eyebrow">Zaufali nam</div><div className="logos"><span>MODÉA</span><span>NovaBud</span><span>GreenLife</span><span>FitZone</span><span>BrightMind</span><span>strefa smaku</span></div></div><div className="trustNumbers"><b>98%<small>klientów poleca nasze usługi</small></b><b>100+<small>zrealizowanych projektów</small></b></div></div></section>
 <section className="section reviewsSection"><div className="wrap testimonials"><div className="reviewsLead"><div className="eyebrow">Co mówią nasi klienci</div><h2>Zaufanie<br/>jest najlepszą<br/>rekomendacją.</h2></div><Review quote="Profesjonalne podejście, świetny kontakt i przepiękny efekt końcowy. Nasza strona przyciąga nowych klientów każdego dnia!" name="Anna Kowalska" brand="MODÉA" initials="AK"/><Review quote="ProjektKreator.pl zrozumiał nasze potrzeby i stworzył stronę, która naprawdę działa. Polecamy z całego serca!" name="Michał Nowak" brand="NovaBud" initials="MN"/><Review quote="Współpraca była czystą przyjemnością. Szybko, konkretnie i z niesamowitym wyczuciem estetyki." name="Katarzyna Zielińska" brand="GreenLife" initials="KZ"/></div></section>
 <CTA go={go} title="Twój projekt może być następny." text="Porozmawiajmy o tym, jak możemy pomóc rozwinąć Twoją markę."/>{demo&&<DemoModal kind={demo} onClose={()=>setDemo(null)}/>}</>}
function Review({quote,name,brand,initials}){return <blockquote><span className="quoteMark">“</span><p>{quote}</p><div className="reviewPerson"><span>{initials}</span><div><b>{name}</b><small>{brand}</small></div></div></blockquote>}

const packs=[['Strona Start','od 599 PLN',['Responsywny wygląd','Do 5 podstron','Formularz kontaktowy','Podstawowe SEO','Szkolenie z obsługi']],['Strona Biznes','od 1 499 PLN',['Do 15 podstron','Indywidualny projekt','Formularze i integracje','Rozszerzone SEO','Wsparcie 3 miesiące']],['Strona Premium','od 2 499 PLN',['Nielimitowane podstrony','Identyfikacja wizualna','Zaawansowane integracje','Pełne SEO','Wsparcie 6 miesięcy']],['Sklep internetowy','od 2 499 PLN',['System płatności','Zarządzanie produktami','Integracje wysyłkowe','Szkolenie','Wsparcie 6 miesięcy']],['Aplikacja webowa','od 3 999 PLN',['Indywidualna wycena','Zaawansowane funkcje','Integracje','Testy i wdrożenie','Opieka powdrożeniowa']]];
function FAQ({items}){const[o,setO]=useState(-1);return <div className="faq">{items.map((x,i)=><div key={x[0]}><button onClick={()=>setO(o===i?-1:i)}>{x[0]}<span>{o===i?'−':'+'}</span></button>{o===i&&<p>{x[1]}</p>}</div>)}</div>}
function Pricing({go}){const faq=[['Czy podane ceny są cenami netto czy brutto?','Szczegóły podatkowe i końcowe rozliczenie ustalamy przed rozpoczęciem projektu.'],['Co jeśli potrzebuję niestandardowych funkcji?','Przygotujemy indywidualną wycenę po analizie zakresu.'],['Czy mogę rozłożyć płatność na etapy?','Tak, płatności mogą odpowiadać kolejnym etapom realizacji.'],['Jak wygląda wycena indywidualna?','Zbieramy wymagania i przedstawiamy zakres, harmonogram i koszt.'],['Czy zapewniacie wsparcie po projekcie?','Tak, oferujemy opiekę i dalszy rozwój.']];return <><Hero eyebrow="Cennik" title={'Przejrzysty<br/>cennik usług.'} text="Wybierz rozwiązanie dopasowane do Twoich potrzeb. Transparentne zasady, brak ukrytych kosztów i pełne wsparcie na każdym etapie współpracy." image={assets.hero_pricing} focus="center"><div className="scribble">Dobre pomysły mają swoją wartość ♡</div></Hero><section className="section tint"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow">Nasze pakiety</div><h2>Wybierz pakiet dla siebie.</h2></div><p>Elastyczne pakiety, które możesz dopasować do swoich celów.</p></div><div className="pricing">{packs.map((p,i)=><article className={'price '+(i===2?'popular':'')} key={p[0]}>{i===2&&<em>NAJCZĘŚCIEJ WYBIERANY</em>}<h3>{p[0]}</h3><div className="bigPrice">{p[1]}</div><ul>{p[2].map(x=><li key={x}>✓ {x}</li>)}</ul><button className="pill" onClick={()=>go('contact')}>{i===4?'Porozmawiajmy →':'Wybieram ten pakiet →'}</button></article>)}</div></div></section><section className="section"><div className="wrap addons"><div><div className="eyebrow">Dodatkowe usługi</div><h2>Rozszerz swój projekt.</h2><p>Potrzebujesz tylko wybranych elementów? Skorzystaj z usług dodatkowych.</p></div>{[['⌁','Debug i poprawki','od 199 PLN'],['⌕','Testowanie QA','od 399 PLN'],['➤','Logo i identyfikacja','od 799 PLN'],['◉','AI i automatyzacje','od 999 PLN']].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><b>{x[2]}</b></article>)}</div></section><section className="section tint"><div className="wrap faqGrid"><div><div className="eyebrow">Najczęściej zadawane pytania</div><h2>Masz pytania<br/>o ceny?</h2></div><FAQ items={faq}/><div className="scribble">Wspólnie tworzymy przestrzeń dla Twoich pomysłów ♡</div></div></section><CTA go={go} title="Nie znalazłeś odpowiedniego pakietu?" text="Opowiedz nam o swoim projekcie, a przygotujemy indywidualną wycenę." button="Napisz do nas →"/></>}

function Contact(){const[sent,setSent]=useState(false);const faq=[['W jakim czasie odpowiadacie?','Najczęściej w ciągu jednego dnia roboczego.'],['Czy wycena jest darmowa?','Tak, wstępna konsultacja i wycena mogą być bezpłatne.'],['Czy mogę najpierw porozmawiać o pomyśle?','Tak — rozmowa pomaga doprecyzować kierunek projektu.'],['Czy realizujecie projekty zdalnie?','Tak, cały proces może być prowadzony zdalnie.']];return <><Hero eyebrow="Kontakt z ProjektKreator.pl" title={'Porozmawiajmy<br/>o Twoim projekcie.'} text="Masz pomysł na stronę, sklep lub aplikację? Napisz do nas — chętnie poznamy Twoje potrzeby i doradzimy najlepsze rozwiązania." image={assets.hero_contact} focus="center"><div className="qualities"><b>◌ Szybka odpowiedź</b><b>♙ Indywidualne podejście</b><b>♡ Wspólnie do celu</b></div></Hero><section className="section tint"><div className="wrap contact"><form onSubmit={e=>{e.preventDefault();setSent(true);e.currentTarget.reset()}}><div className="eyebrow">Napisz do nas</div><h2>Wyślij nam wiadomość</h2><div className="formGrid"><label>Imię i nazwisko *<input required placeholder="np. Anna Kowalska"/></label><label>Adres e-mail *<input required type="email" placeholder="np. anna@twojafirma.pl"/></label><label>Numer telefonu<input placeholder="opcjonalnie"/></label><label>Rodzaj projektu *<select required defaultValue=""><option value="" disabled>Wybierz z listy</option><option>Strona internetowa</option><option>Sklep online</option><option>Aplikacja webowa</option><option>AI i automatyzacje</option></select></label><label className="full">Wiadomość *<textarea required placeholder="Opisz krótko swój pomysł, cele i wymagania..."/></label><label className="check full"><input type="checkbox" required/> Wyrażam zgodę na przetwarzanie danych w celu odpowiedzi na wiadomość.</label></div><button className="pill" type="submit">Wyślij wiadomość →</button>{sent&&<div className="success">Dziękujemy! Formularz działa w interfejsie. Następnym krokiem będzie podłączenie wysyłki do backendu.</div>}</form><aside><h2>Co dzieje się po wysłaniu wiadomości?</h2>{[['✉','Potwierdzamy otrzymanie'],['☵','Analizujemy Twoje potrzeby'],['▤','Przedstawiamy propozycję'],['♡','Zaczynamy działać']].map(x=><div className="after" key={x[1]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</aside></div></section><section className="section"><div className="wrap faqGrid"><div><div className="eyebrow">Najczęściej zadawane pytania</div><h2>Masz pytania?<br/>Mamy odpowiedzi.</h2></div><FAQ items={faq}/><img className="note" src={assets.contact_note}/></div></section></>}

export default function App(){const initial=()=>{const h=location.hash.replace('#','');return nav.some(x=>x[0]===h)?h:'services'};const[page,setPage]=useState(initial);const go=p=>{setPage(p);history.replaceState(null,'','#'+p);window.scrollTo({top:0,behavior:'instant'})};useEffect(()=>{const f=()=>setPage(initial());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return <><Header page={page} go={go}/><main>{page==='services'&&<Services go={go}/>} {page==='portfolio'&&<Portfolio go={go}/>} {page==='pricing'&&<Pricing go={go}/>} {page==='contact'&&<Contact/>}</main><Footer go={go}/></>}
